AllCops:
  Include:
    - Berksfile
    - '**/Gemfile'
    - Rakefile
    - Thorfile
    - Guardfile
  Exclude:
    - vendor/**

ClassLength:
  Enabled: false
Documentation:
  Enabled: false
Encoding:
  Enabled: false
HashSyntax:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
SignalException:
  Enabled: false
Style/TrailingCommaInArguments:
  Enabled: false
WordArray:
  Enabled: false
ClassAndModuleChildren:
  Enabled: false
AbcSize:
  Enabled: false
Style/SpaceBeforeFirstArg:
  Enabled: false
